---
name: End-To-End Tests
'on':
  push:
    branches:
      - feat_end_to_end_tests_with_github_actions
jobs:
  test:
    name: End-To-End Tests
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.x
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright dependencies
        run: |
          npx playwright install chromium --with-deps       
      - name: Create .env file
        run: |
          echo "SMTP2GO_API_KEY=${{secrets.SMTP2GO_API_KEY}}" > .env
      - name: Install WordPress and start the server
        run: |
          npm run wp-env start          
      - name: Running End-To-End Tests Against Default Config
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          npm run test:playwright
      - name: Create wp env override file
        run: |
          echo "{"\"phpVersion\"": "\"8.1\""}" > .wp-env.override.json
      - name: Running End-To-End Tests Against PHP 8.1
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          npm run wp-env start --update
          npm run test:playwright
      - name: Running End-To-End Tests Against PHP 8.2
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          echo "{"\"phpVersion\"": "\"8.2\""}" > .wp-env.override.json
          npm run wp-env start --update
          npm run test:playwright